module.exports = [
    {
        id: 0,
        name: 'Lorem ipsum.',
        price: 499,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        quantity: 2,
    },
    {
        id: 1,
        name: 'Lorem ipsum.',
        price: 499,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        quantity: 10,
    },
    {
        id: 2,
        name: 'Dolor',
        price: 499,
        description: 'Morbi et sapien eget lectus sollicitudin volutpat.',
        quantity: 10,
    },
    {
        id: 3,
        name: 'Sit amet',
        price: 499,
        description: 'Phasellus dignissim diam dapibus, sagittis metus finibus, ultricies purus.',
        quantity: 10,
    },
    {
        id: 4,
        name: 'Consectetur ',
        price: 499,
        description: 'Proin congue elit id maximus laoreet.',
        quantity: 10,
    },
    {
        id: 5,
        name: 'Adipiscing ',
        price: 499,
        description: 'Nulla elementum sem at urna consectetur, id luctus purus lobortis.',
        quantity: 10,
    },
    {
        id: 6,
        name: 'Elit',
        price: 70,
        description: 'Fusce aliquam urna nec ligula ullamcorper ultricies.',
        quantity: 50,
    },
    {
        id: 7,
        name: 'Sed',
        price: 60,
        description: 'Nullam lacinia justo quis augue semper, et aliquam ligula cursus.',
        quantity: 20,
    },
    {
        id: 8,
        name: 'Quis',
        price: 500,
        description: 'Vestibulum vitae dolor sit amet erat mattis hendrerit quis nec felis.',
        quantity: 69,
    },
    {
        id: 9,
        name: 'Justo ',
        price: 499,
        description: 'Vivamus commodo enim nec luctus iaculis.',
        quantity: 2,
    },
    {
        id: 10,
        name: 'suscipit',
        price: 70,
        description: 'Pellentesque vel ex eget enim commodo porttitor.',
        quantity: 50,
    },
    {
        id: 11,
        name: 'Porttitor',
        price: 60,
        description: 'Integer a urna a risus volutpat interdum nec quis tortor.',
        quantity: 20,
    },
    {
        id: 12,
        name: 'Porttitor',
        price: 60,
        description: 'Integer a urna a risus volutpat interdum nec quis tortor.',
        quantity: 20,
    },
    {
        id: 13,
        name: 'Nunc tempor',
        price: 500,
        description: 'Sed ac arcu sed dolor cursus bibendum ac nec diam.',
        quantity: 69,
    },
    {
        id: 14,
        name: 'Vivamus eu mi mollis',
        price: 500,
        description: 'Proin mattis justo in nulla tempor posuere.',
        quantity: 69,
    },
    {
        id: 15,
        name: 'Nulla gravida',
        price: 500,
        description: 'Maecenas consectetur purus vel venenatis sollicitudin.',
        quantity: 69,
    },
];
